# Generated by Django 4.2.2 on 2023-06-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
